repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: mixed-line-ending
        args:
          - --fix=no
      - id: no-commit-to-branch
        args:
          - --branch=master
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

