name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --max-line-length=200 --disable=C0103,C0114,C0115,C0116,C0301,R0903,R0913,R1735,E0401 --output-format=colorized --variable-rgx="[a-z_][a-z0-9_]{0,30}$" --function-rgx="[a-z_][a-z0-9_]{0,30}$" --max-branches=15 --disable=logging-not-lazy,no-logging-else-logging --ignore-comments=yes --ignore-docstrings=yes $(git ls-files 'cells/streamlit/*.py')
